# chart-testing configuration
# https://github.com/helm/chart-testing

chart-dirs:
  - charts

validate-maintainers: false
check-version-increment: true

# Use custom yamllint config
lint-conf: .github/yamllint.yaml

# Helm lint settings
helm-extra-args: --timeout 600s
