changelog:
  categories:
    - title: "New Features"
      labels:
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Removed"
      labels:
        - removed
  exclude:
    labels:
      - skip-changelog
