{{- if .Values.nomad.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-proxy
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- if include "nomad.ingress.traefikCRs" . }}
  annotations:
    # Backend timeouts for Traefik; see templates/ingress-traefik.yaml
    traefik.ingress.kubernetes.io/service.serverstransport: {{ include "nomad.ingress.traefikRef" (dict "root" . "name" "transport") }}
  {{- end }}
spec:
  type: {{ .Values.nomad.proxy.service.type }}
  ports:
    - port: {{ .Values.nomad.proxy.service.port }}
      # targetPort: http
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "nomad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
{{- end}}